PPMecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from .forms import LoginForm

app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
    path("research/", views.research, name="research"),
    path("details/<int:pk>/", views.details, name="details"),
    path("signup/", views.signup, name="signup"),
    path("login/", auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm),
         name='login'),
    path('logout/', views.logout_view, name='logout'),
    path("cart/", views.cart, name="cart"),
    path("checkout/", views.checkout, name="checkout"),
    path("update_cart/", views.updateCart, name="update_cart"),
    path("process_order/", views.processOrder, name="process_order"),
    path("profile/", views.profile, name="profile"),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.
class Customer(models.Model):
    class Meta:
        ordering = ("name",)
        verbose_name_plural = "Customers"

    user = models.OneToOneField(User, null=True, blank=True, related_name='customer', on_delete=models.CASCADE)
    name = models.CharField(max_length=255, null=True)
    surname = models.CharField(max_length=255, null=True)
    email = models.CharField(max_length=255, null=True)

    def __str__(self):
        return self.name


@receiver(post_save, sender=User)
def assign_customer(sender, instance, created, **kwargs):
    if created:
        customer = Customer.objects.create(user=instance)
        customer.name = instance.first_name
        customer.surname = instance.last_name
        customer.email = instance.email

        customer.save()


class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ("name",)
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name


class SubCategory(models.Model):
    name = models.CharField(max_length=255)
    category = models.ForeignKey(Category, related_name='subCategories', on_delete=models.CASCADE)

    class Meta:
        ordering = ("name",)
        verbose_name_plural = "subCategories"

    def __str__(self):
        return self.name


class Seller(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ("name",)
        verbose_name_plural = "Sellers"

    def __str__(self):
        return self.name


class Product(models.Model):
    class Meta:
        ordering = ("name",)
        verbose_name_plural = "Products"

    name = models.CharField(max_length=255)
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    description = models.TextField(blank=True, null=True)
    seller = models.ForeignKey(Seller, related_name='products', on_delete=models.CASCADE)
    subCategory = models.ForeignKey(SubCategory, related_name='products', on_delete=models.CASCADE, default=1)
    price = models.FloatField()
    is_sold = models.BooleanField(default=False)
    image = models.ImageField(upload_to="static/media", blank=True, null=True)

    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, blank=False, null=True)
    transaction_id = models.CharField(max_length=255, null=True)

    def __str__(self):
        return str(self.id)

    @property
    def get_cart_total(self):
        items_ordered = self.orderitem_set.all()
        total = 0
        for item in items_ordered:
            total += item.get_total
        return total

    @property
    def get_cart_items(self):
        items_quantity = self.orderitem_set.all()
        total = 0
        for item in items_quantity:
            total += item.quantity
        return total


class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, blank=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True, blank=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    added_time = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total


class Address(models.Model):
    class Meta:
        ordering = ("address",)
        verbose_name_plural = "Address"

    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True, blank=True)
    state = models.CharField(max_length=255, null=True)
    city = models.CharField(max_length=255, null=True)
    zipcode = models.CharField(max_length=255, null=True)
    address = models.CharField(max_length=255, null=True)

    def __str__(self):
        return self.address

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your Username',
        'class': "w-full py-4 px-6 rounded-xl"
    }))
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your Name',
        'class': "w-full py-4 px-6 rounded-xl"
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your Surname',
        'class': "w-full py-4 px-6 rounded-xl"
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your Email Address',
        'class': "w-full py-4 px-6 rounded-xl"
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your Password',
        'class': "w-full py-4 px-6 rounded-xl"
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your Password Again',
        'class': "w-full py-4 px-6 rounded-xl"
    }))


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your Username',
        'class': "w-full py-4 px-6 rounded-xl"
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your Password',
        'class': "w-full py-4 px-6 rounded-xl"
    }))

core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from .forms import SignupForm, LoginForm
from django.http import JsonResponse
import json, datetime
from .models import *
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth import login
from django.contrib.auth import logout


# Create your views here.
def index(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        ordname = order.id
        items = order.orderitem_set.all()
        cartitems = order.get_cart_items
    else:
        items = []
        order = {'get_cart_total': 0, 'get_cart_items': 0}
        cartitems = order['get_cart_items']
        ordname = {'ordname': ''}

    products = Product.objects.all()
    context = {'products': products, 'cartitems': cartitems, 'ordname': ordname}

    return render(request, 'core/index.html', context)


def research(request):
    query = request.GET.get('query', '')
    idcategory = request.GET.get('category', 0)
    products = Product.objects.filter(is_sold=False)
    categories = Category.objects.all()
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        cartitems = order.get_cart_items
    else:
        order = {'get_cart_total': 0, 'get_cart_items': 0}
        cartitems = order['get_cart_items']

    if idcategory:
        products = products.filter(category_id=idcategory)

    if query:
        products = products.filter(
            Q(name__icontains=query) | Q(description__icontains=query) | Q(category__name__icontains=query) | Q(
                subCategory__name__icontains=query))

    context = {'products': products, 'query': query, 'cartitems': cartitems, 'categories': categories,
               'idcategory': int(idcategory)}
    return render(request, 'core/research.html', context)


def details(request, pk):
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        cartitems = order.get_cart_items
    else:
        order = {'get_cart_total': 0, 'get_cart_items': 0}
        cartitems = order['get_cart_items']

    item = get_object_or_404(Product, pk=pk)
    context = {'item': item, 'cartitems': cartitems}

    return render(request, 'core/details.html', context)


def cart(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()
        cartitems = order.get_cart_items
    else:
        items = []
        order = {'get_cart_total': 0, 'get_cart_items': 0}
        cartitems = order['get_cart_items']

    context = {'items': items, 'order': order, 'cartitems': cartitems}
    return render(request, 'core/cart.html', context)


@csrf_protect
def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/cart/')
    else:
        form = SignupForm()  # GET case

    order = {'get_cart_total': 0, 'get_cart_items': 0}
    cartitems = order['get_cart_items']
    context = {'form': form, 'cartitems': cartitems}
    return render(request, 'core/signup.html', context)


@csrf_protect
def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)

        if form.is_valid():
            user = form.get_user()
            login(request, user)

            return redirect('/index/')
        else:
            form = LoginForm()

    order = {'get_cart_total': 0, 'get_cart_items': 0}
    cartitems = order['get_cart_items']
    context = {'form': form, 'cartitems': cartitems}

    return render(request, 'core/login.html', context)


@csrf_protect
def logout_view(request):
    logout(request)
    return redirect('/login/')


def checkout(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()
        cartitems = order.get_cart_items
    else:
        items = []
        order = {'get_cart_total': 0, 'get_cart_items': 0}
        cartitems = order['get_cart_items']

    context = {'items': items, 'order': order, 'cartitems': cartitems}
    return render(request, 'core/checkout.html', context)


def updateCart(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']
    print('productId: ', productId)
    print('Action: ', action)

    customer = request.user.customer
    product = Product.objects.get(id=productId)
    order, created = Order.objects.get_or_create(customer=customer, complete=False)

    orderitem, created = OrderItem.objects.get_or_create(order=order, product=product)

    if action == 'add':
        orderitem.quantity = (orderitem.quantity + 1)
    elif action == 'remove':
        orderitem.quantity = (orderitem.quantity - 1)

    orderitem.save()

    if orderitem.quantity <= 0:
        orderitem.delete()
    return JsonResponse('Item was ' + action.__str__(), safe=False)


def processOrder(request):
    transactionId = datetime.datetime.now().timestamp()
    data = json.loads(request.body)

    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        total = float(data['form']['total'])
        order.transaction_id = transactionId

        if total == order.get_cart_total:
            order.complete = True
        order.save()

        Address.objects.get_or_create(
            customer=customer,
            order=order,
            address=data['shipping']['address'],
            city=data['shipping']['city'],
            state=data['shipping']['state'],
            zipcode=data['shipping']['zipcode'],
        )
    else:
        print('User not logged in')
    print('Data: ', request.body)
    return JsonResponse('Payment Complete!', safe=False)


def profile(request):
    customer = request.user.customer
    order, created = Order.objects.get_or_create(customer=customer, complete=False)
    cartitems = order.get_cart_items
    if request.method == 'POST':
        user = request.user
        user.username = request.POST['username']
        user.first_name = request.POST['first_name']
        user.last_name = request.POST['last_name']
        user.email = request.POST['email']
        user.save()

    orders = Order.objects.filter(customer=customer)

    context = {'cartitems': cartitems, 'orders': orders}
    return render(request, 'core/profile.html', context)

templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script type="text/javascript">
        var user = '{{ request.user }}'

        function getToken(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                    }
                }
            }
            return cookieValue;
        }
        const csrftoken = getToken('csrftoken');

    </script>

    <title>{% block title %}{% endblock %} | New Page</title>
</head>

<body>
    <nav class="py-6 px-6 flex justify-between items-center bg-gray-800">
        <a href="/" class="text-2xl font-semibold text-teal-500 border-2 rounded-lg p-2 border-teal-500
                            hover:text-white hover:border-white">Home</a>

        <a href="{% url "core:research" %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-gray-700">Ricerca Avanzata</a>
        <form method="get" action="{% url "core:research" %}" >
            <div class="flex justify-center">
                <label>
                    <input name="query" class="rounded-l-lg py-2 px-4 border-t mr-0 border-b border-l text-gray-800
                                 border-gray-200 bg-white" type="text" value="{{ query }}" placeholder="Cerca...">
                </label>
                <button class="px-4 bg-teal-500 text-white font-semibold rounded-r-lg border-t border-b border-r">Cerca</button>
            </div>
        </form>
        <div class="flex items-center space-x-4">
            {% if request.user.is_authenticated %}
                <a href="{% url "core:logout" %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-gray-700">Logout</a>
                <a href="{% url "core:profile" %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-gray-700">Profilo</a>
            {% else %}
                <a href="{% url "core:signup" %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign Up</a>
                <a href="{% url "core:login" %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-gray-700">Login</a>
            {% endif %}
            <div class="relative ml-4 h-10 w-10 place-items-center">
                <a href="{% url "core:cart" %}">
                    <img src="{% static "media/cart.png" %}" alt="Carrello" class="h-10 w-10 hover:h-9 hover:w-9">
                    <span class="absolute top-0 right-0 bg-red-500 text-white rounded-full w-4 h-4 flex items-center justify-center text-xs">{{ cartitems }}</span>
                </a>
            </div>
        </div>

    </nav>
    <div class="px-6 py-6">
        {%  block content %}
        {% endblock %}
    </div>

    <footer class="py-6 px-6 flex justify-between bg-gray-800">
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-400">About</h3>

            <p class="text-gray-500">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed iaculis pulvinar finibus. Vivamus finibus
                id ante sed laoreet. Nulla metus est, accumsan sed tincidunt ut, ornare nec nibh. Nullam euismod,
                arcu vitae consequat mattis, eros odio consequat elit, eget rhoncus elit enim non tortor.
                Maecenas pulvinar interdum magna, commodo ultrices mauris convallis sed.
                Pellentesque mollis vulputate hendrerit. Donec sed nibh quis velit convallis scelerisque eget ac libero.
                Nullam sed auctor elit. Mauris molestie sed sapien ac mollis. Nunc et scelerisque justo.
                Fusce ornare dictum imperdiet. Donec pulvinar, nulla vel dapibus commodo, tortor ex tristique lectus,
                id blandit ligula neque at neque.</p>
        </div>

        <div class="1/3">
            <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

            <ul class="space-y-2">
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a> </li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Contact</a> </li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy policy</a> </li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Term of use</a> </li>
            </ul>
        </div>
    </footer>

    <script src="https://cdn.tailwindcss.com"></script>

    <script type="text/javascript" src="{% static "js/cart.js" %}"></script>
</body>
</html>

templates/core/cart.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}Cart{% endblock %}

{% block content %}
    <a href="{% url "core:index" %}" class="inline-flex pb-6">
        <button class="flex items-center justify-center bg-white border border-black rounded-full px-4 py-2 text-black hover:text-gray-800 hover:bg-gray-200 transition-colors">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-2 transform rotate-180" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd" d="M11.707 14.707a1 1 0 010-1.414L14.586 10H7a1 1 0 010-2h7.586l-2.293-2.293a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd" />
            </svg>
            Continua lo shopping
        </button>
    </a>
<div class="bg-gray-100">
  <div class="max-w-7xl mx-auto px-4 py-6">
      <h1 class="text-2xl font-bold mb-4">Carrello</h1>
      <div class="mb-4">
          <h2 class="text-xl font-semibold mb-2">Prodotti nel carrello</h2>
          <div class="bg-white rounded shadow">
              {% for item in items %}
                  <div class="flex items-center justify-between border-b border-gray-300 py-3 px-4">
                      <div class="flex  align-center space-x-10">
                          <div class="flex-1">
                              <h3 class="text-lg font-semibold">{{ item.product.name }}</h3>
                              <p class="text-gray-800 font-semibold">Prezzo: ${{ item.product.price|floatformat:2 }}</p>
                              <div class="flex align-center ">
                                  <div class="flex items-center">
                                      <div class="text-gray-800 font-semibold">Quantità:</div>
                                      <div class="rounded border border-gray-500 ml-2 p-1">
                                           {{ item.quantity }}
                                      </div>
                                  </div>
                                  <div class="flex-column items-center ml-2 mt-1">
                                      <button id="updatecart" data-product="{{ item.product.id }}" data-action="add" class="flex button mb-1">
                                          <img src="{% static "media/arrow-up.png"%}" class="h-3 w-3 cursor-pointer hover:opacity-75" alt="Freccia su">
                                      </button>
                                      <button id="updatecart" data-product="{{ item.product.id }}" data-action="remove" class="flex button mb-1">
                                          <img src="{% static "media/arrow-down.png"%}" class="h-3 w-3 cursor-pointer hover:opacity-75" alt="Freccia giù">
                                      </button>
                                  </div>
                              </div>
                          </div>
                          <div class="flex items-center w-20">
                              <a href="{% url "core:details" item.product.id %}" class="object-contain">
                                <img src="{{ item.product.imageURL}}" alt="">
                              </a>
                          </div>
                      </div><p class="text-gray-600">${{ item.get_total }}</p>
                  </div>
              {% endfor %}
          </div>
      </div>
      <div class="bg-white rounded shadow p-4"><h2 class="text-xl font-semibold mb-2">Riepilogo carrello</h2>
          <div class="flex items-center justify-between py-3">
              <p class="text-lg font-semibold">Prodotti</p>
              <p class="text-lg font-semibold">{{ order.get_cart_items }}</p>
          </div><div class="flex items-center justify-between border-b border-gray-300 py-3">
              <p class="text-lg font-semibold">Totale</p>
              <p class="text-lg font-semibold">${{ order.get_cart_total|floatformat:2 }}</p>
          </div>
          {% if order.get_cart_items > 0 %}
            <a href="{% url 'core:checkout' %}">
                <button class="bg-teal-500 hover:bg-teal-600 text-white font-semibold py-2 px-4 rounded mt-4">Procedi al pagamento</button>
            </a>
          {% endif %}
      </div>
  </div>
</div>
{% endblock %}

templates/core/checkout.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}Cart{% endblock %}

{% block content %}
    <a href="{% url "core:cart" %}" class="inline-flex">
        <button class="flex items-center justify-center bg-white border border-black rounded-full px-4 py-2 text-black hover:text-gray-800 hover:bg-gray-200 transition-colors">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-2 transform rotate-180" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd" d="M11.707 14.707a1 1 0 010-1.414L14.586 10H7a1 1 0 010-2h7.586l-2.293-2.293a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd" />
            </svg>
            Torna al carrello
        </button>
    </a>
    <div class="bg-gray-200 mt-8 rounded-xl min-h-screen">
        <div class="container mx-auto py-8 px-8">
           <h1 class="text-3xl font-semibold mb-8">Checkout</h1>

            <div class="grid grid-cols-2 gap-8 ">
                <div class="bg-white p-6 rounded-lg shadow-md">
                    <h2 class="text-xl font-semibold mb-4">Informazioni di recapito</h2>
                    <form id="form" class="grid gap-4">
                        <div id="userinfo" class="grid grid-cols-2 gap-4 border border-gray-300 pb-4">
                            <div class="mb-4">
                              <label for="name" class="block text-sm font-medium text-gray-700">Name</label>
                              <input type="text" id="name" name="name" class="form-input mt-1 block w-full" placeholder="Mario" required>
                            </div>
                            <div class="mb-4">
                              <label for="email" class="block text-sm font-medium text-gray-700">Email</label>
                              <input type="text" id="name" name="Email" class="form-input mt-1 block w-full" placeholder="Mario@email.com" required>
                            </div>
                            <div class="mb-4">
                                <label for="surname" class="block text-sm font-medium text-gray-700">Surname</label>
                                <input type="text" id="name" name="Surname" class="form-input mt-1 block w-full" placeholder="Rossi" required>
                            </div>
                        </div>
                        <div id="shippinginfo">
                            <div  class="grid grid-cols-2 gap-4">
                                <div class="mb-4">
                                  <label for="address" class="block text-sm font-medium text-gray-700 ">Address</label>
                                  <input type="text" id="address" name="" class="form-input mt-1 block w-full border border-gray-300 rounded" placeholder="via Roma" required>
                                </div>
                                <div class="mb-4">
                                  <label for="city" class="block text-sm font-medium text-gray-700">City</label>
                                  <input type="text" id="city" name="city" class="form-input mt-1 block w-full border border-gray-300 rounded" placeholder="Roma" required>
                                </div>
                                <div class="mb-4">
                                  <label for="state" class="block text-sm font-medium text-gray-700">State</label>
                                  <input type="text" id="state" name="state" class="form-input mt-1 block w-full border border-gray-300 rounded" placeholder="Italia" required>
                                </div>
                                <div class="mb-4">
                                  <label for="zipcode" class="block text-sm font-medium text-gray-700">Zipcode</label>
                                  <input type="text" id="zipcode" name="zipcode" class="form-input mt-1 block w-full border border-gray-300 rounded" placeholder="20022" required>
                                </div>
                            </div>

                            <button id="pay" class="bg-teal-500 text-white px-4 py-2 rounded-lg hover:bg-teal-600 hidden">Place Order</button>
                        </div>
                        <input id="form_submit" type="submit" class="py-2 px-4 bg-teal-500 hover:bg-teal-600 text-white font-semibold rounded-lg cursor-pointer" value="Conferma">
                    </form>

                </div>

                <div class="bg-white p-6 rounded-lg shadow-md">
                    <h2 class="text-xl font-semibold mb-4">Order Summary</h2>
                    <div>
                        {%  for item in items %}
                        <div class="flex items-center justify-between border-b border-gray-300 mb-4">
                            <div class="flex items-center">
                                <img src="{{ item.product.imageURL }}" class="h-20 w-20 object-contain rounded-lg" alt="Product Image">
                                <div class="ml-4">
                                    <p>{{ item.product.name }}</p>
                                    <p>{{ item.product.category }}</p>
                                    <p>{{ item.quantity }}</p>
                                </div>
                            </div>
                            <p>${{ item.product.price }}</p>
                        </div>
                        {% endfor %}
                    </div>

                    <div class="flex justify-between">
                      <p class="text-lg font-semibold">Products:</p>
                      <p class="text-lg">{{ order.get_cart_items }}</p>
                    </div>
                    <div class="flex justify-between">
                      <p class="text-lg font-semibold">Total:</p>
                      <p class="text-lg">${{ order.get_cart_total|floatformat:2 }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript">

        if (user !== 'AnonymousUser'){
            document.getElementById("userinfo").innerHTML = ''
            document.getElementById("userinfo").classList.add("hidden")
        }

        var inputs = document.querySelectorAll('input[type="text"]')
        const form = document.getElementById("form")
        const total = '{{ order.get_cart_total }}'

        form.addEventListener('submit', function(e){
            e.preventDefault()
            document.getElementById("form_submit").classList.add("hidden")
            for (let i=0; i<inputs.length; i++){
                inputs[i].setAttribute('readonly', 'readonly')
            }
            document.getElementById("pay").classList.remove("hidden")
        })

        document.getElementById('pay').addEventListener('click', function(e){
            checkoutFormData()
        })
        function checkoutFormData(){
            console.log('payment button clicked')

            const userformdata = {
                'name':null,
                'surname':null,
                'email':null,
                'total': total
            }

            const addressformdata = {
                'address': null,
                'city': null,
                'state': null,
                'zipcode': null,
            }

            addressformdata.address = form.address.value
            addressformdata.city = form.city.value
            addressformdata.state = form.state.value
            addressformdata.zipcode = form.zipcode.value

            //per sicurezza
            if(user === 'AnonymousUser'){
                userformdata.name = form.name.value
                userformdata.surname = form.surname.value
                userformdata.email = form.email.value
            }

            var url = ' /process_order/'
            fetch(url, {
                method: 'POST',
                headers: {
                    'Content-Type' : 'application/json',
                    'X-CSRFToken' : csrftoken,
                },
                body: JSON.stringify({
                    'form':userformdata,
                    'shipping': addressformdata
                }),
            })
            .then((response) => response.json())
            .then((data) => {
                console.log('Success:', data);
                alert('Transaction Complete');
                window.location.href = "{% url 'core:index' %}";
            })
        }

    </script>
{% endblock %}